### ISSUE TITLE
add application-head.js

### ISSUE THREAD

**Issue by reubenmoes** [domain7/gruntyplate#1]
This is needed so we can make sure modernizr is loaded in the head. Other scripts can be loaded before body tag

**Comment by nathansh** [comment]
➕❶, 👍, good idea.

**Comment by reubenmoes** [comment]
🍪🍪🍪🍫🍬🍭

**Comment by reubenmoes** [comment]
Added this.  But in addition to this, I removed concat, and the plate now uses uglify to concatenate the file.  What this means is you will no longer have application.js and application.min.js.  You will just have application.js, which will be minified by default, or if you turn off the beautify or mangle options you can have a non-minified file.  The cool part about this is that sourcemaps will point to the actual source file as opposed to a line in the concatenated application.js file.  Yay!
